### GET request to example server
GET https://mwmd-af-webpubsub.azurewebsites.net/api/WebPubSubEventOccured?code=okfnrsnaf0z_43VXnpXTeCiitAEVRj3DuMcxxc-JV0qcAzFulNWWpA%3D%3D

### Here is a comment about what this does
GET https://mwmd-af-webpubsub.azurewebsites.net/api/WebPubSubEventOccured?code=okfnrsnaf0z_43VXnpXTeCiitAEVRj3DuMcxxc-JV0qcAzFulNWWpA%3D%3D
